export {
    getData,
    FETCH_SMURF_DATA_START,
    FETCH_SMURF_DATA_SUCCESS,
    FETCH_SMURF_DATA_FAILURE,
    deleteData,
    DELETE_SMURF_DATA_START,
    DELETE_SMURF_DATA_SUCCESS,
    DELETE_SMURF_DATA_FAILURE,
    editData,
    EDIT_SMURF_DATA_START,
    EDIT_SMURF_DATA_SUCCESS,
    EDIT_SMURF_DATA_FAILURE,
    SEND_SMURF_DATA_START,
    SEND_SMURF_DATA_SUCCESS,
    SEND_SMURF_DATA_FAILURE,
    sendData
} from './smurfActions.js'